In [124]:
# General:
import tweepy           # To consume Twitter's API
import pandas as pd     # To handle data
import numpy as np      # For number computing

# For plotting and visualization:
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

In [125]:
# Consume:
CONSUMER_KEY    = 'XXX'
CONSUMER_SECRET = 'XXX'

# Access:
ACCESS_TOKEN  = 'XX-XX'
ACCESS_SECRET = 'XXX'

In [126]:
# API's setup:
def twitter_setup():
    """
    Utility function to setup the Twitter's API
    with our access keys provided.
    """
    # Authentication and access using keys:
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)


    # Return API with authentication:
    api = tweepy.API(auth, wait_on_rate_limit=True)
    return api

In [127]:
 #We create an extractor object:
extractor = twitter_setup()

# We create a tweet list as follows:
tweets = extractor.user_timeline(screen_name="KuduKSA", count=2000)
print("Number of tweets extracted: {}.\n".format(len(tweets)))

# We print the most recent 5 tweets:
print("5 recent tweets:\n")
for tweet in tweets[:5]:
    print(tweet.text)
    print()

Number of tweets extracted: 200.

5 recent tweets:

@hamada_859 موجودين لكم دائمًا ، تنورونا ونتطلع لخدمتكم 😍❤️❤️

أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة لين عندك! 😍👨🏻‍💻 #كودو https://t.co/1m6scLbfFJ

@AhmadAlshehri حياك، مايرضينا اللي صار نم رفع الشكوى للادارة، وان شاء لله نكون عند حسن ظنك ..🌷

@yalla1234 @f_a5y ابشري، تواصلنا معك💕

@yalla1234 حياك، تواصلنا معك على الخاص💕

In [128]:
# We create a pandas dataframe as follows:
data = pd.DataFrame(data=[tweet.text for tweet in tweets], columns=['Tweets'])

# We display the first 10 elements of the dataframe:
display(data.head(10))

                                              Tweets
0  @hamada_859 موجودين لكم دائمًا ، تنورونا ونتطل...
1  أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة ...
2  @AhmadAlshehri حياك، مايرضينا اللي صار نم رفع ...
3              @yalla1234 @f_a5y ابشري، تواصلنا معك💕
4            @yalla1234 حياك، تواصلنا معك على الخاص💕
5  @khaledalotib حياك، سنوصل رأيك للإدارة المعنية...
6            @9dfh8 هلافيك، ب٢٠ ريال وبالعافية عليك💕
7              @sc_r70 حياك، تواصلنا معك على الخاص❤️
8  @Magicallight88 حياك، بالعافية عليك ابشري بنرف...
9  تعرّف على أشهى علبة 😍👆🏼أطلب إفطار كودو أو ستيك...

In [129]:
# We create a pandas dataframe as follows:
data = pd.DataFrame(data=[tweet.text for tweet in tweets], columns=['Tweets'])

# We display the first 10 elements of the dataframe:
display(data.head(10))

                                              Tweets
0  @hamada_859 موجودين لكم دائمًا ، تنورونا ونتطل...
1  أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة ...
2  @AhmadAlshehri حياك، مايرضينا اللي صار نم رفع ...
3              @yalla1234 @f_a5y ابشري، تواصلنا معك💕
4            @yalla1234 حياك، تواصلنا معك على الخاص💕
5  @khaledalotib حياك، سنوصل رأيك للإدارة المعنية...
6            @9dfh8 هلافيك، ب٢٠ ريال وبالعافية عليك💕
7              @sc_r70 حياك، تواصلنا معك على الخاص❤️
8  @Magicallight88 حياك، بالعافية عليك ابشري بنرف...
9  تعرّف على أشهى علبة 😍👆🏼أطلب إفطار كودو أو ستيك...

In [130]:
# Internal methods of a single tweet object:
print(dir(tweets[0]))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_api', '_json', 'author', 'contributors', 'coordinates', 'created_at', 'destroy', 'entities', 'favorite', 'favorite_count', 'favorited', 'geo', 'id', 'id_str', 'in_reply_to_screen_name', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'is_quote_status', 'lang', 'parse', 'parse_list', 'place', 'retweet', 'retweet_count', 'retweeted', 'retweets', 'source', 'source_url', 'text', 'truncated', 'user']

In [131]:
print(tweets[0].entities)
print(tweets[0].id)
print(tweets[0].created_at)
print(tweets[0].source)
print(tweets[0].favorite_count)
print(tweets[0].retweet_count)
print(tweets[0].geo)
print(tweets[0].coordinates)
print(tweets[0].in_reply_to_status_id)
print(tweets[0].in_reply_to_status_id_str)
print(tweets[0].is_quote_status)
print(tweets[0].author)

{'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'hamada_859', 'name': 'احمدو 📷🏃🏻\u200d♂️', 'id': 1028378484270424064, 'id_str': '1028378484270424064', 'indices': [0, 11]}], 'urls': []}
1353982081697779714
2021-01-26 08:24:18
Twitter for iPhone
0
0
None
None
1353818683823583232
1353818683823583232
False
User(_api=<tweepy.api.API object at 0x000002575D023248>, _json={'id': 273969669, 'id_str': '273969669', 'name': 'Kudu | كـودو', 'screen_name': 'KuduKSA', 'location': 'Saudi Arabia', 'description': 'طعم تذوقه بعينك | خدمة التوصيل في المملكة 920006999', 'url': 'https://t.co/pqUyCO9Y6H', 'entities': {'url': {'urls': [{'url': 'https://t.co/pqUyCO9Y6H', 'expanded_url': 'http://www.kudu.com.sa/home', 'display_url': 'kudu.com.sa/home', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 273056, 'friends_count': 0, 'listed_count': 173, 'created_at': 'Tue Mar 29 13:41:01 +0000 2011', 'favourites_count': 1517, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True, 'statuses_count': 48852, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '022330', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1309968586644086785/zukSylTa_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1309968586644086785/zukSylTa_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/273969669/1610683464', 'profile_link_color': 'FAB81E', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': 'C0DFEC', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'regular'}, id=273969669, id_str='273969669', name='Kudu | كـودو', screen_name='KuduKSA', location='Saudi Arabia', description='طعم تذوقه بعينك | خدمة التوصيل في المملكة 920006999', url='https://t.co/pqUyCO9Y6H', entities={'url': {'urls': [{'url': 'https://t.co/pqUyCO9Y6H', 'expanded_url': 'http://www.kudu.com.sa/home', 'display_url': 'kudu.com.sa/home', 'indices': [0, 23]}]}, 'description': {'urls': []}}, protected=False, followers_count=273056, friends_count=0, listed_count=173, created_at=datetime.datetime(2011, 3, 29, 13, 41, 1), favourites_count=1517, utc_offset=None, time_zone=None, geo_enabled=False, verified=True, statuses_count=48852, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='022330', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1309968586644086785/zukSylTa_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1309968586644086785/zukSylTa_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/273969669/1610683464', profile_link_color='FAB81E', profile_sidebar_border_color='000000', profile_sidebar_fill_color='C0DFEC', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=False, default_profile=False, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='regular')

In [132]:
data['len']  = np.array([len(tweet.text) for tweet in tweets])
data['ID']   = np.array([tweet.id for tweet in tweets])
data['Date'] = np.array([tweet.created_at for tweet in tweets])
data['Source'] = np.array([tweet.source for tweet in tweets])
data['Likes']  = np.array([tweet.favorite_count for tweet in tweets])
data['RTs']    = np.array([tweet.retweet_count for tweet in tweets])
data['favorite']    = np.array([tweet.favorite_count for tweet in tweets])
data['in_reply_to_status_id'] = np.array([tweet.in_reply_to_status_id for tweet in tweets])
data['in_reply_to_status_id_str'] = np.array([tweet.in_reply_to_status_id_str for tweet in tweets])
data['in_reply_to_status_id'] = np.array([tweet.in_reply_to_status_id for tweet in tweets])

In [133]:
print(data)

                                                Tweets  len  \
0    @hamada_859 موجودين لكم دائمًا ، تنورونا ونتطل...   61
1    أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة ...   91
2    @AhmadAlshehri حياك، مايرضينا اللي صار نم رفع ...   94
3                @yalla1234 @f_a5y ابشري، تواصلنا معك💕   37
4              @yalla1234 حياك، تواصلنا معك على الخاص💕   39
..                                                 ...  ...
195         @MZX_5522 حياك ، رفعنا ملاحظتك للإدارة 🙏🏻🤍   42
196  @HussinYG20000 ياهلا ، يمكنك الارسال للإيميل H...   70
197  @b_alatas7 مرحبا ،نرجو منك تزويدنا بالمزيد من ...  140
198                      @RANAD51562622 تم الرد عليك❤️   29
199  @thlij 😍❤️تسلم يدك على هالتصوير الاكثر من رائع...   70

                      ID                Date              Source  Likes  RTs  \
0    1353982081697779714 2021-01-26 08:24:18  Twitter for iPhone      0    0
1    1353975966629056515 2021-01-26 08:00:00     Twitter Web App      0    0
2    1353963132587286528 2021-01-26 07:09:00  Twitter for iPhone      0    0
3    1353962867557625856 2021-01-26 07:07:57  Twitter for iPhone      0    0
4    1353962778025930752 2021-01-26 07:07:36  Twitter for iPhone      0    0
..                   ...                 ...                 ...    ...  ...
195  1349897435515150341 2021-01-15 01:53:23  Twitter for iPhone      0    0
196  1349897357450735621 2021-01-15 01:53:04  Twitter for iPhone      1    0
197  1349866789291905030 2021-01-14 23:51:36  Twitter for iPhone      0    0
198  1349866645808947200 2021-01-14 23:51:02  Twitter for iPhone      0    0
199  1349866565974581256 2021-01-14 23:50:43  Twitter for iPhone      1    0

     favorite in_reply_to_status_id in_reply_to_status_id_str
0           0   1353818683823583232       1353818683823583232
1           0                  None                      None
2           0   1353811230897668098       1353811230897668098
3           0   1353814117136691202       1353814117136691202
4           0   1353814338449137664       1353814338449137664
..        ...                   ...                       ...
195         0   1349839299118825472       1349839299118825472
196         1   1349832967791775745       1349832967791775745
197         0   1349756195406544900       1349756195406544900
198         0   1349768865128054790       1349768865128054790
199         1   1349777443029213184       1349777443029213184

[200 rows x 10 columns]

In [134]:
data.head(10)

,Tweets,len,ID,Date,Source,Likes,RTs,favorite,in_reply_to_status_id,in_reply_to_status_id_str
0,@hamada_859 موجودين لكم دائمًا ، تنورونا ونتطل...,61,1353982081697779714,2021-01-26 08:24:18,Twitter for iPhone,0,0,0,1353818683823583232,1353818683823583232
1,أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة ...,91,1353975966629056515,2021-01-26 08:00:00,Twitter Web App,0,0,0,None,None
2,@AhmadAlshehri حياك، مايرضينا اللي صار نم رفع ...,94,1353963132587286528,2021-01-26 07:09:00,Twitter for iPhone,0,0,0,1353811230897668098,1353811230897668098
3,@yalla1234 @f_a5y ابشري، تواصلنا معك💕,37,1353962867557625856,2021-01-26 07:07:57,Twitter for iPhone,0,0,0,1353814117136691202,1353814117136691202
4,@yalla1234 حياك، تواصلنا معك على الخاص💕,39,1353962778025930752,2021-01-26 07:07:36,Twitter for iPhone,0,0,0,1353814338449137664,1353814338449137664
5,@khaledalotib حياك، سنوصل رأيك للإدارة المعنية...,69,1353962650368167936,2021-01-26 07:07:05,Twitter for iPhone,0,0,0,1353831168010022913,1353831168010022913
6,@9dfh8 هلافيك، ب٢٠ ريال وبالعافية عليك💕,39,1353962468289228807,2021-01-26 07:06:22,Twitter for iPhone,0,0,0,1353899062718828544,1353899062718828544
7,@sc_r70 حياك، تواصلنا معك على الخاص❤️,37,1353962039161606144,2021-01-26 07:04:40,Twitter for iPhone,0,0,0,1353931512283082759,1353931512283082759
8,@Magicallight88 حياك، بالعافية عليك ابشري بنرف...,94,1353961815215140864,2021-01-26 07:03:46,Twitter for iPhone,1,0,1,1353939237809360896,1353939237809360896
9,تعرّف على أشهى علبة 😍👆🏼أطلب إفطار كودو أو ستيك...,140,1353915566277468165,2021-01-26 04:00:00,Twitter for Advertisers,0,0,0,None,None

In [135]:
data = data.fillna(value=np.nan)

In [136]:
data.fillna("missing")

,Tweets,len,ID,Date,Source,Likes,RTs,favorite,in_reply_to_status_id,in_reply_to_status_id_str
0,@hamada_859 موجودين لكم دائمًا ، تنورونا ونتطل...,61,1353982081697779714,2021-01-26 08:24:18,Twitter for iPhone,0,0,0,1.35382e+18,1353818683823583232
1,أطلب من خلال #موقع_كودو وخلينا نوصلّك اللذاذة ...,91,1353975966629056515,2021-01-26 08:00:00,Twitter Web App,0,0,0,missing,missing
2,@AhmadAlshehri حياك، مايرضينا اللي صار نم رفع ...,94,1353963132587286528,2021-01-26 07:09:00,Twitter for iPhone,0,0,0,1.35381e+18,1353811230897668098
3,@yalla1234 @f_a5y ابشري، تواصلنا معك💕,37,1353962867557625856,2021-01-26 07:07:57,Twitter for iPhone,0,0,0,1.35381e+18,1353814117136691202
4,@yalla1234 حياك، تواصلنا معك على الخاص💕,39,1353962778025930752,2021-01-26 07:07:36,Twitter for iPhone,0,0,0,1.35381e+18,1353814338449137664
...,...,...,...,...,...,...,...,...,...,...
195,@MZX_5522 حياك ، رفعنا ملاحظتك للإدارة 🙏🏻🤍,42,1349897435515150341,2021-01-15 01:53:23,Twitter for iPhone,0,0,0,1.34984e+18,1349839299118825472
196,@HussinYG20000 ياهلا ، يمكنك الارسال للإيميل H...,70,1349897357450735621,2021-01-15 01:53:04,Twitter for iPhone,1,0,1,1.34983e+18,1349832967791775745
197,@b_alatas7 مرحبا ،نرجو منك تزويدنا بالمزيد من ...,140,1349866789291905030,2021-01-14 23:51:36,Twitter for iPhone,0,0,0,1.34976e+18,1349756195406544900
198,@RANAD51562622 تم الرد عليك❤️,29,1349866645808947200,2021-01-14 23:51:02,Twitter for iPhone,0,0,0,1.34977e+18,1349768865128054790
199,@thlij 😍❤️تسلم يدك على هالتصوير الاكثر من رائع...,70,1349866565974581256,2021-01-14 23:50:43,Twitter for iPhone,1,0,1,1.34978e+18,1349777443029213184

In [137]:
IDs=[]
for index, row in data.iterrows():
    if '@' not in row['Tweets']:
        IDs.append(row['ID'])

In [138]:
print(IDs)

[1353975966629056515, 1353915566277468165, 1353809876896473097, 1353553178462019594, 1352888802289840128, 1352662314042839040, 1352239766394335232, 1351575147833036800, 1351454350405738497, 1351439250584203264, 1351076878828748800, 1351016465344966657, 1350759776536375296, 1350714474467094529, 1350654077785444352, 1350352087213858816, 1350291687650717696, 1350185991261233154, 1349929301563457540]

In [145]:
IDs2=IDs[:2]

In [148]:
print(IDs2)

[1353975966629056515, 1353915566277468165]

In [142]:
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
api = tweepy.API(auth, wait_on_rate_limit=True)

In [158]:
name = 'KuduKSA'
tweet_id = '1353915566277468165'
replies=[]
for tweet in tweepy.Cursor(api.search,q='to:'+name, result_type='recent', timeout=999999).items(1000):
    if hasattr(tweet, 'in_reply_to_status_id_str'):
        if (tweet.in_reply_to_status_id_str==tweet_id):
            replies.append(tweet)

In [161]:
with open('replies_clean.csv', "w", encoding='utf-8') as f:
    csv_writer = csv.DictWriter(f, fieldnames=('user', 'text'))
    csv_writer.writeheader()
    for tweet in replies:
        row = {'user': tweet.user.screen_name, 'text': tweet.text.replace('\n', ' ')}
        csv_writer.writerow(row)

In [162]:
def replies_function(name,tweet_id):
    replies=[]
    for tweet in tweepy.Cursor(api.search,q='to:'+name, result_type='recent', timeout=999999).items(1000):
        if hasattr(tweet, 'in_reply_to_status_id_str'):
            if (tweet.in_reply_to_status_id_str==tweet_id):
                replies.append(tweet)
    return replies

In [163]:
i==1
for num in IDs2:
    reply=replies_function(name='KuduKSA',tweet_id=str(num))
    with open('replies_clean'+str(i)+'.csv', 'w',encoding='utf-8') as f:
        csv_writer = csv.DictWriter(f, fieldnames=('user', 'text'))
        csv_writer.writeheader()
        for tweet in reply:
            row = {'user': tweet.user.screen_name, 'text': tweet.text.replace('\n', ' ')}
            csv_writer.writerow(row)
    i=i+1

In [165]:
df0=pd.read_csv('replies_clean0.csv')
df1=pd.read_csv('replies_clean1.csv')

In [166]:
df0.head()

        user                                               text
0    N_Rooo7  @KuduKSA طلبت من التطبيق ووضعت خيار استلام الط...
1  fahad9508  @KuduKSA هاتو شيف شاطر بالطبخ مره الشيف اللي ع...

In [167]:
df2=pd.read_csv('replies_clean*.csv')

FileNotFoundError: [Errno 2] File b'replies_clean*.csv' does not exist: b'replies_clean*.csv'

In [ ]:
for i in